name: install-pnpm


runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: 🔧 Install PNPM
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7

    - name: Install dependencies
      uses: ./.github/templates/load-deps

    - name: ♻️ Restore ESLint Cache
      uses: actions/cache@v3
      id: eslint-cache
      with:
        path: .eslintcache
        key: ${{ matrix.os }}-eslint-${{ hashFiles('**/*.ts', 'package.json', 'tsconfig.json') }}

    - name: 🚨 Lint files
      run: pnpm run lint

