name: load-deps


runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: ♻️ Restore node_modules
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: 🛠️ Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
        check-latest: true
        cache: 'pnpm'

    - name: ⚙️ Install dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install --prefer-offline
      shell: bash
