name: install-deps


runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  name: 📦 Install dependencies
  steps:
    - name: Install pnpm
      uses: '.github/.templates/install-pnpm'

    - name: ♻️ Cache node_modules
      uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 🛠️ Setup Node and install project dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
        check-latest: true
        cache: 'pnpm'

      if: steps.pnpm-cache.outputs.cache-hit != 'true'
    - run: pnpm install --prefer-offline
