name: build-prod


runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  name:  ⚒ Build
  steps:
    - name: lint and install deps
      uses: ./.github/templates/lint-package

    - name: 🧪 Run tests
      run: pnpm run test:ci

    - name: ⚒️ Build package
      run: pnpm run build



