name: build-prod


runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: lint and install deps
      uses: ./.github/templates/lint-package

    - name: 🧪 Run tests
      run: pnpm run test:ci
      shell: bash

    - name: ⚒️ Build package
      run: pnpm run build
      shell: bash



